const NON_BRANDED_ITEM_NAMES = [
  'sugar',
  'चीनी',
  'rice',
  'चावल',
  'wheat flour',
  'आटा',
  'besan',
  'बेसन',
  'rava',
  'रवा',
  'semolina',
  'सूजी',
  'dal',
  'daal',
  'dall',
  'दाल',
  'arhar dal',
  'अरहर दाल',
  'toor dal',
  'तूर दाल',
  'masoor dal',
  'मसूर दाल',
  'moong dal',
  'मूंग दाल',
  'urad dal',
  'उड़द दाल',
  'chana dal',
  'चना दाल',
  'chana',
  'चना',
  'rajma',
  'राजमा',
  'turmeric powder',
  'हल्दी पाउडर',
  'red chilli',
  'लाल मिर्च',
  'coriander powder',
  'धनिया पाउडर',
  'cumin',
  'जीरा',
  'mustard seeds',
  'सरसों',
  'garam masala',
  'गरम मसाला',
  'mustard oil',
  'सरसों तेल',
  'sunflower oil',
  'सूरजमुखी तेल',
  'sesame oil',
  'तिल का तेल',
  'soybean',
  'सोयाबीन',
  'vermicelli',
  'सेवइ',
  'maida',
  'मैदा',
  'black pepper',
  'काली मिर्च',
  'cardamom',
  'इलायची',
  'cinnamon',
  'दालचीनी',
  'cloves',
  'लौंग',
  'baking powder',
  'बेकिंग पाउडर',
  'baking soda',
  'बेकिंग सोडा',
  'flattened rice',
  'चूडा',
  'wheat',
  'गेहूँ',
  'potato',
  'आलू',
  'onion',
  'प्याज',
  'garlic',
  'लहसुन',
  'tomato',
  'टमाटर',
  'banana',
  'केला',
  'apple',
  'सेब',
  'oil',
  'तेल',
  'peanuts',
  'मूंगफली',
  'cashews',
  'काजू',
  'almonds',
  'बादाम',
  'fox nuts',
  'मखाना',
  'cocoa drink',
  'चॉकलेट ड्रिंक',
  'coffee',
  'कॉफी',
  'milk',
  'दूध',
  'curd',
  'दही',
  'butter',
  'मक्खन',
  'ghee',
  'घी',
  'chips',
  'चिप्स',
  'namkeen',
  'नमकीन',
  'masala chips',
  'मसाला चिप्स',
  'kurkure',
  'कुरकुरे',
  'cookies',
  'बिस्किट',
  'chocolate',
  'चॉकलेट',
];

const normalizeItemName = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/\s*\([^)]*\)\s*/g, ' ')
    .replace(/[^a-z0-9\s\u0900-\u097f]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

export const isBrandApplicableForItem = (itemName: string): boolean => {
  const normalized = normalizeItemName(itemName);

  if (!normalized) {
    return true;
  }

  return !NON_BRANDED_ITEM_NAMES.some(name => {
    const candidate = normalizeItemName(name);
    return candidate === normalized;
  });
};
